name: Convert new folders in Test/text

on:
  push:
    branches: [feature]
    paths:
      - 'Test/text/**'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Detect added/changed folders in Test/text
        id: detect
        run: |
          # 変更されたファイルから親ディレクトリ名だけ抽出
          git diff --name-status HEAD^ HEAD | \
            grep '^A\|^M' | \
            awk '{print $2}' | \
            grep '^Test/text/' | \
            awk -F/ '{print $3}' | \
            sort | uniq > changed_dirs.txt

          echo "Changed dirs:"
          cat changed_dirs.txt

      - name: Run Rust conversion on each folder
        run: |
          while read dir; do
            echo "Processing folder: $dir"
            cargo run --release --manifest-path convert_to_json/Cargo.toml -- "../Test/text/$dir"
          done < changed_dirs.txt

      - name: Commit and push JSON output
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add Test/json/
          git commit -m "Add JSON from pushed folder(s)"
          git push origin HEAD:${{ github.ref_name }}

