name: Convert new folders in Test/text

on:
  push:
    branches: [ feature ]
    paths: [ 'Test/text/**' ]
  pull_request:
    branches: [ feature ]
    paths:  [ 'Test/text/**' ]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # 変更ディレクトリ抽出
      - name: Get changed dirs
        id: changed_dirs
        run: |
          dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- Test/text/ |
                 grep -E '^Test/text/[^/]+/?' |
                 cut -d/ -f3 | sort -u)
          echo "folders=$dirs" >> "$GITHUB_OUTPUT"

      # Rust を実行
      - name: Run Rust per sub-folder
        continue-on-error: true
        if: steps.changed_dirs.outputs.folders != ''
        run: |
          for f in ${{ steps.changed_dirs.outputs.folders }}; do
            echo "▶️ Processing $f"
            cargo run --release -- "../Test/text/$f" || echo "Rust failed for $f"
          done

      # 生成物をコミット
      - name: Commit converted JSON
        if: steps.changed_dirs.outputs.folders != ''
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Test/json
          if git diff --cached --quiet; then
            echo "No new JSON to commit"
            exit 0
          fi
          git commit -m "chore(json): auto-generate from Rust"
          git push
