name: Convert ALL folders in Test/text

on:
  push:
    branches: [ feature ]
    paths:  [ 'Test/text/**' ]   # 変更があれば起動
  pull_request:
    branches: [ feature ]
    paths:  [ 'Test/text/**' ]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 後で push するため

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # --- Rust をフォルダごとに実行 ---
      - name: Run Rust for every folder in Test/text
        continue-on-error: true       # どこか失敗してもジョブ継続
        run: |
          for dir in Test/text/*/ ; do
            folder=$(basename "$dir")               # 例: test1
            echo "Processing $folder"
            cargo run --release -- "../Test/text/$folder" \
              || echo "Rust failed for $folder"
          done

      # --- 生成物をコミット ---
      - name: Commit converted JSON
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Test/json
          if git diff --cached --quiet; then
            echo "No new JSON to commit"
            exit 0
          fi
          git commit -m "chore(json): auto-generate from Rust (all folders)"
          git push
